param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$TargetDir,[string]$GoldenManifest,[string]$CurrentManifest)
$ErrorActionPreference='Stop';if(!$GoldenManifest){$GoldenManifest=Join-Path $RepoRoot 'docs\baselines\1.26.2.1-BAT.sha256'};if(!$CurrentManifest){$CurrentManifest=Join-Path $RepoRoot 'config\build\current-resource-manifest.sha256'}
function Hash([string]$Path){
  if(!(Test-Path -LiteralPath $Path -PathType Leaf)){throw "hash input missing: $Path"}
  $sha=[Security.Cryptography.SHA256]::Create();$stream=$null
  try{$stream=[IO.File]::OpenRead($Path);return (([BitConverter]::ToString($sha.ComputeHash($stream)) -replace '-','').ToUpperInvariant())}
  catch{throw "hash failed: $Path : $($_.Exception.Message)"}
  finally{if($stream){$stream.Dispose()};$sha.Dispose()}
}
function ReadM($p){$d=@{};$n=0;foreach($l in Get-Content -LiteralPath $p){$n++;if($l -match '^\s*(#|$)'){continue};$x=$l.Trim() -split '\s+',3;if($x.Count -ne 2 -or $x[0] -notmatch '^[0-9A-Fa-f]{64}$'){throw "invalid manifest line ${n}: $l"};$r=$x[1].TrimStart('*') -replace '/','\';if([IO.Path]::IsPathRooted($r) -or $r -match '(^|\\)\.\.(\\|$)'){throw "unsafe path ${n}: $r"};if($d.ContainsKey($r)){throw "duplicate path: $r"};$d[$r]=$x[0].ToUpperInvariant()};if(!$d.Count){throw "manifest empty: $p"};return $d}
$g=ReadM $GoldenManifest;$c=ReadM $CurrentManifest;$all=@{};foreach($r in $g.Keys){if($r -like 'swf\*'){$all[$r]=@($g[$r],'golden baseline')}};foreach($r in $c.Keys){if($r -like 'swf\*'){$all[$r]=@($c[$r],'current manifest')}};if($all.Count -ne 175){throw "resource plan count mismatch: $($all.Count)"}
$stage="$TargetDir.__stage";if(Test-Path $stage){Remove-Item $stage -Recurse -Force};New-Item $stage -ItemType Directory -Force|Out-Null
try{$seen=@{};foreach($r in $all.Keys){$src=Join-Path $RepoRoot $r;if(!(Test-Path -LiteralPath $src)){$src=Join-Path (Join-Path $RepoRoot 'swf') ([IO.Path]::GetFileName($r))};if(!(Test-Path -LiteralPath $src)){throw "missing resource: $r"};if($r -notlike 'swf\*'){throw "unsupported resource root: $r"};$targetRel=$r.Substring(4);if([IO.Path]::IsPathRooted($targetRel) -or $targetRel -match '(^|\\)\.\.(\\|$)' -or [string]::IsNullOrWhiteSpace($targetRel)){throw "unsafe target path: $r"};$dst=Join-Path $stage $targetRel;$full=[IO.Path]::GetFullPath($dst);if($seen.ContainsKey($full)){throw "duplicate target: $r"};$seen[$full]=$true;$h=(Hash $src);if($h -ine $all[$r][0]){throw "hash mismatch: $r"};Write-Output "[CHECK] $r -> $targetRel ($($all[$r][1]))";New-Item (Split-Path $dst) -ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath $src -Destination $dst;if((Hash $dst) -ine $h){throw "copy hash mismatch: $r"}};if(Test-Path $TargetDir){Remove-Item $TargetDir -Recurse -Force};Move-Item $stage $TargetDir;if(Test-Path (Join-Path $TargetDir 'swf\arms1100.swf')){throw "unexpected nested target: swf\arms1100.swf"};Write-Output "[OK] Runtime resources prepared: $($all.Count)"}catch{if(Test-Path $stage){Remove-Item $stage -Recurse -Force};Write-Error $_;exit 1}
